version: '2'
services:
    web1:
        build: ./nginx
        volumes:
         - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
         - /var/www/sites:/var/www/sites
         - /var/log/nginx:/var/log/nginx
        ports:
         - "80:80"
        links:
         - phpfpm
         - mariadatabase
    mariadatabase:
        build: ./mariadb
        volumes:
         - /var/log/mysql:/var/log/mysql
         - /var/lib/mysql:/var/lib/mysql
        environment:
         - MYSQL_ROOT_PASSWORD=matkhaudedoan
        ports:
         - "3306:3306"
    phpfpm:
        build: ./php-56fpm
        volumes:
         - /var/log/php:/var/log/php
         - /var/www/sites:/var/www/sites
         - /home/download/phalcon-devtools:/home/download/phalcon-devtools
        ports:
         - "9000:9000"
            
